services:
  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge